In [55]:
import os
import numpy as np
import json
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Get required data
From the github repository

In [ ]:
# Clone the entire repo.
!git clone -l -s https://github.com/XLipcak/rev-rec.git cloned-repo

fatal: destination path 'cloned-repo' already exists and is not an empty directory.


In [ ]:
%ls

cloned-repo/  drive/  openstack.json  sample_data/


In [ ]:
# Save OpenStack dataset
import shutil
src = "/content/cloned-repo/rev-rec-data/openstack.json"
dst = "/content/drive/MyDrive/Colab Notebooks/My Project/openstack.json"
shutil.move(src, dst)

FileNotFoundError: ignored

# Read json file

In [ ]:
f = open('/content/drive/MyDrive/Colab Notebooks/My Project/openstack.json',)
data = json.load(f)  # returns json object as a dictionary
for i in range(5):   # 5 first elements of the json list
    print(data[i])
f.close()

{'subProject': 'openstack/tempest', 'changeId': 'I9e7b9a2491d6a3f01d71551e4cadcccf154d992d', 'changeNumber': 6139, 'timestamp': 1333428006000, 'reviewers': [{'accountId': '97', 'email': 'daryl.walleck@rackspace.com', 'name': 'Daryl Walleck', 'avatar': None}, {'accountId': '7', 'email': 'jaypipes@gmail.com', 'name': 'Jay Pipes', 'avatar': None}], 'owner': {'accountId': '2238', 'email': 'rajalakshmi.girish@hpe.com', 'name': 'rajalakshmi-ganesan', 'avatar': None}, 'filePaths': [{'location': 'tempest/tests/test_volumes_get.py'}]}
{'subProject': 'openstack/tempest', 'changeId': 'I10e7116570f922ec87e23b1f880cd4b1c08c3088', 'changeNumber': 7438, 'timestamp': 1337072165000, 'reviewers': [{'accountId': '97', 'email': 'daryl.walleck@rackspace.com', 'name': 'Daryl Walleck', 'avatar': None}, {'accountId': '7', 'email': 'jaypipes@gmail.com', 'name': 'Jay Pipes', 'avatar': None}], 'owner': {'accountId': '4120', 'email': 'rohit.karajgi@ril.com', 'name': 'Rohit Karajgi', 'avatar': None}, 'filePaths': 

## Hands on with given data

In [ ]:
type(data)

list

In [ ]:
len(data)

6545

In [ ]:
# get an element of the list of data
data[0]

{'changeId': 'I9e7b9a2491d6a3f01d71551e4cadcccf154d992d',
 'changeNumber': 6139,
 'filePaths': [{'location': 'tempest/tests/test_volumes_get.py'}],
 'owner': {'accountId': '2238',
  'avatar': None,
  'email': 'rajalakshmi.girish@hpe.com',
  'name': 'rajalakshmi-ganesan'},
 'reviewers': [{'accountId': '97',
   'avatar': None,
   'email': 'daryl.walleck@rackspace.com',
   'name': 'Daryl Walleck'},
  {'accountId': '7',
   'avatar': None,
   'email': 'jaypipes@gmail.com',
   'name': 'Jay Pipes'}],
 'subProject': 'openstack/tempest',
 'timestamp': 1333428006000}

In [ ]:
# read a single feature of an element
data[0]['reviewers']

[{'accountId': '97',
  'avatar': None,
  'email': 'daryl.walleck@rackspace.com',
  'name': 'Daryl Walleck'},
 {'accountId': '7',
  'avatar': None,
  'email': 'jaypipes@gmail.com',
  'name': 'Jay Pipes'}]

In [ ]:
# Get the Time of available data from selected project
from datetime import datetime
  
timestamp = data[0]['timestamp']
dt_obj = datetime.fromtimestamp(1333428006).strftime('%y-%m-%d')  # should drop the 3 last zero digits
print("End   time:", timestamp, "is equal to date:", dt_obj)

timestamp = data[6544]['timestamp']
dt_obj = datetime.fromtimestamp(1311695026).strftime('%y-%m-%d')
print("Start time:", timestamp, "is equal to date:", dt_obj)

End   time: 1333428006000 is equal to date: 12-04-03
Start time: 1311695026000 is equal to date: 11-07-26


The openstack data that we use in here, containes about 8 months information of openstack project (2011-2012)

## Cleaning data

In [ ]:
# Extract and save desired features from each pull request. The new desired data is new_data
new_data = []

for i in range(0, len(data)):
  elem_dict = {"changeId":data[i]['changeId'], "reviewers":data[i]['reviewers'], "owner":data[i]['owner'], "filePaths":data[i]['filePaths']}
  new_data.append(elem_dict)
  # print(new_data[i])

print(len(new_data))

6545


In [ ]:
new_data[0]

{'changeId': 'I9e7b9a2491d6a3f01d71551e4cadcccf154d992d',
 'filePaths': [{'location': 'tempest/tests/test_volumes_get.py'}],
 'owner': {'accountId': '2238',
  'avatar': None,
  'email': 'rajalakshmi.girish@hpe.com',
  'name': 'rajalakshmi-ganesan'},
 'reviewers': [{'accountId': '97',
   'avatar': None,
   'email': 'daryl.walleck@rackspace.com',
   'name': 'Daryl Walleck'},
  {'accountId': '7',
   'avatar': None,
   'email': 'jaypipes@gmail.com',
   'name': 'Jay Pipes'}]}

In [ ]:
# Remove remaining undesired features. The final desired information is saved in final_data
final_data = []

for i in range(0, len(new_data)):
  elem_dict = {"changeId":new_data[i]['changeId'], "ownerId": new_data[i]['owner']['accountId'], "reviewersId":[], "filePaths":[]}

  for j in range(0, len(new_data[i]['reviewers'])):
    elem_dict["reviewersId"].append(new_data[i]['reviewers'][j]['accountId'])

  for j in range(0, len(new_data[i]['filePaths'])):
    elem_dict["filePaths"].append(new_data[i]['filePaths'][j]['location'])
  
  final_data.append(elem_dict)
  # print(final_data[i])

print(len(final_data))

6545


In [ ]:
final_data[1]

{'changeId': 'I10e7116570f922ec87e23b1f880cd4b1c08c3088',
 'filePaths': ['tempest/tests/identity/test_roles.py',
  'tempest/services/identity/json/admin_client.py',
  'tempest/tests/identity/base_admin_test.py'],
 'ownerId': '4120',
 'reviewersId': ['97', '7']}

In [ ]:
type(final_data)

list

In [ ]:
# Convert list to json
# It should be a string before write it to file
json_string = json.dumps(final_data)

# Save OpenStack new dataset
file = open('openstack_final.json', 'w')
file.write(json_string)
file.close()

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
# Move OpenStack dataset to proper location
import shutil

src = "./openstack_final.json"
dst = "/content/drive/MyDrive/Colab Notebooks/My Project/openstack_final.json"
shutil.move(src, dst)

'/content/drive/MyDrive/Colab Notebooks/My Project/openstack_final.json'

# Approach

Should run the code each time from this part

## Load final data and split

In [133]:
# Load final data from drive
f = open('/content/drive/MyDrive/Colab Notebooks/My Project/openstack_final.json',)
data = json.load(f)  # returns json object as a dictionary
for i in range(5):   # 5 first elements of the json list
    print(data[i])
f.close()

{'changeId': 'I9e7b9a2491d6a3f01d71551e4cadcccf154d992d', 'ownerId': '2238', 'reviewersId': ['97', '7'], 'filePaths': ['tempest/tests/test_volumes_get.py']}
{'changeId': 'I10e7116570f922ec87e23b1f880cd4b1c08c3088', 'ownerId': '4120', 'reviewersId': ['97', '7'], 'filePaths': ['tempest/tests/identity/test_roles.py', 'tempest/services/identity/json/admin_client.py', 'tempest/tests/identity/base_admin_test.py']}
{'changeId': 'I1d0c395cf679e07e304dd878d97734307b685f4c', 'ownerId': '1849', 'reviewersId': ['679', '1561'], 'filePaths': ['.gitignore']}
{'changeId': 'Ia151f265bf62e6704de6cc2f2c01963be9e2dd69', 'ownerId': '1849', 'reviewersId': ['1561', '357'], 'filePaths': ['tools/hacking.py']}
{'changeId': 'Ie4cfec6f89d6b37554b5345cde92f982397915e2', 'ownerId': '2', 'reviewersId': ['1561', '357'], 'filePaths': ['tox.ini']}


In [134]:
# Split data for train/test sets
init_train = data[0:5900]     # 90% of data is for initial train set (5900 PR)
total_test = data[5900:6545]  # 10% of data will be tested in the whole examination (645 PR)

## Main components of the approach
Extract 3 interaction metrices

### Reviewer's **expertise** model

#### step by step

In [100]:
all_files = set()   # make a "set" of all file paths. we selected set to prevent collecting repeated files
for pr in train:
  for f in pr['filePaths']:
    all_files.add(f)

len(all_files)

10653

In [101]:
all_reviewers = set()   # make a set of all reviewers
for pr in train:
  for r in pr['reviewersId']:
    all_reviewers.add(r)

len(all_reviewers)

82

In [102]:
# create a dataframe that its first column is all existing files
df = pd.DataFrame(all_files)
df.head()

0
0  nova/db/sqlalchemy/migrate_repo/versions/067_s...
1                   melange/client/views/__init__.py
2  openstack-identity-api/src/docbkx/common/sampl...
3                            keystoneclient/shell.py
4                         tests/test_backend_ldap.py

In [103]:
df = df.rename(columns={0:'file'})
df.head()

file
0  nova/db/sqlalchemy/migrate_repo/versions/067_s...
1                   melange/client/views/__init__.py
2  openstack-identity-api/src/docbkx/common/sampl...
3                            keystoneclient/shell.py
4                         tests/test_backend_ldap.py

In [104]:
# add a column of zeros for each existing reviewer to dataframe
for r in all_reviewers:
  df[r] = 0

df.head()

file  321  24  ...  1998  1699  2284
0  nova/db/sqlalchemy/migrate_repo/versions/067_s...    0   0  ...     0     0     0
1                   melange/client/views/__init__.py    0   0  ...     0     0     0
2  openstack-identity-api/src/docbkx/common/sampl...    0   0  ...     0     0     0
3                            keystoneclient/shell.py    0   0  ...     0     0     0
4                         tests/test_backend_ldap.py    0   0  ...     0     0     0

[5 rows x 83 columns]

In [105]:
# fill the values of dataframe by checking PRs one by one
for pr in train:
  for f in pr['filePaths']:
    for r in pr['reviewersId']:
      df.loc[(df['file'] == f), r] += 1

df.head()

file  321  24  ...  1998  1699  2284
0  nova/db/sqlalchemy/migrate_repo/versions/067_s...    0   0  ...     0     0     0
1                   melange/client/views/__init__.py    0   0  ...     0     0     0
2  openstack-identity-api/src/docbkx/common/sampl...    0   0  ...     0     0     0
3                            keystoneclient/shell.py    0   0  ...     0     0     0
4                         tests/test_backend_ldap.py    0   0  ...     0     0     0

[5 rows x 83 columns]

In [108]:
df = df.set_index('file')
df.head()

321  24  ...  1699  2284
file                                                         ...            
nova/db/sqlalchemy/migrate_repo/versions/067_sq...    0   0  ...     0     0
melange/client/views/__init__.py                      0   0  ...     0     0
openstack-identity-api/src/docbkx/common/sample...    0   0  ...     0     0
keystoneclient/shell.py                               0   0  ...     0     0
tests/test_backend_ldap.py                            0   0  ...     0     0

[5 rows x 82 columns]

In [110]:
# convert the dataframe into matrix
FR = df.to_numpy()
FR.shape

(10653, 82)

#### All together
as 'cal_expertise' function

In [135]:
# Function to extract 'Expertise' metrix
# Returns P*M matrix named FR
def cal_expertise(train, test):

  # create a "set" of all file paths. we selected set to prevent collecting repeated files
  all_files = set()   
  for pr in train:
    for f in pr['filePaths']:
      all_files.add(f)
  print("P is:", len(all_files))

  # create a set of all reviewers
  all_reviewers = set()   
  for pr in train:
    for r in pr['reviewersId']:
      all_reviewers.add(r)
  print("M is:", len(all_reviewers))

  # create a dataframe that its first column is all existing files
  df = pd.DataFrame(all_files)  
  df = df.rename(columns={0:'file'})  # set a name for this column

  # add a column of zeros for each existing reviewer to dataframe
  for r in all_reviewers:
    df[r] = 0

  # fill the cells of the dataframe by checking PRs one by one
  for pr in train:
    for f in pr['filePaths']:
      for r in pr['reviewersId']:
        df.loc[(df['file'] == f), r] += 1

  # convert the dataframe into matrix
  df = df.set_index('file')
  FR = df.to_numpy()
  print("Shape of FR matrix is:", FR.shape)
  return FR

### Reviewer‑developer **collaboration** model

#### step by step

In [125]:
all_devs = set()   # make a "set" of all developers
for pr in train:
  for d in pr['ownerId']:
    all_devs.add(d)

len(all_devs)

10

In [126]:
len(all_reviewers)

82

In [128]:
# create a dataframe that its first column is all existing developers
df = pd.DataFrame(all_devs)
df = df.rename(columns={0:'developer'})
df

developer
0         5
1         9
2         7
3         3
4         6
5         1
6         8
7         2
8         0
9         4

In [129]:
# add a column of zeros for each existing reviewer to dataframe
for r in all_reviewers:
  df[r] = 0

df.head()

developer  321  24  100  67  494  1247  ...  706  233  330  2472  1998  1699  2284
0         5    0   0    0   0    0     0  ...    0    0    0     0     0     0     0
1         9    0   0    0   0    0     0  ...    0    0    0     0     0     0     0
2         7    0   0    0   0    0     0  ...    0    0    0     0     0     0     0
3         3    0   0    0   0    0     0  ...    0    0    0     0     0     0     0
4         6    0   0    0   0    0     0  ...    0    0    0     0     0     0     0

[5 rows x 83 columns]

In [130]:
# fill the values of dataframe by checking PRs one by one
for pr in train:
  for r in pr['reviewersId']:
    df.loc[(df['developer'] == pr['ownerId']), r] += len(pr['filePaths'])

df.head()

developer  321  24  100  67  494  1247  ...  706  233  330  2472  1998  1699  2284
0         5    0   0    0   2    0     0  ...    0    0    0     0     0     0     0
1         9    0   0    0   0    0     0  ...    0    0    0     0     0     0     0
2         7    0   0    0   7    0     0  ...    8    0    0     0     0     0     0
3         3   58   0   76  40    0    40  ...    0    0    0     0     0     0     0
4         6    0   0    0   2    7     0  ...    0    0    0     0     0     0     0

[5 rows x 83 columns]

In [131]:
df = df.set_index('developer')
# convert the dataframe into matrix
DR = df.to_numpy()
DR.shape

(10, 82)

#### All together
as 'cal_collaboration' function

In [136]:
# Function to extract 'Collaboration' metrix
# Returns N*M matrix named DR
def cal_collaboration(train, test):

  # create a "set" of all developers
  all_devs = set()  
  for pr in train:
    for d in pr['ownerId']:
      all_devs.add(d)
  print("N is:", len(all_devs))

  # There is a set of all reviewers
  print("M is:", len(all_reviewers))

  # create a dataframe that its first column is all existing developers
  df = pd.DataFrame(all_devs)
  df = df.rename(columns={0:'developer'})

  # add a column of zeros for each existing reviewer to dataframe
  for r in all_reviewers:
    df[r] = 0
  
  # fill the values of dataframe by checking PRs one by one
  for pr in train:
    for r in pr['reviewersId']:
      df.loc[(df['developer'] == pr['ownerId']), r] += len(pr['filePaths'])

  # convert the dataframe into matrix
  df = df.set_index('developer')
  DR = df.to_numpy()
  print("Shape of DR matrix is:", DR.shape)
  return DR

## Test

In [137]:
for test_num in range(0, 1):  # number of examination can be 0 to 644
  # creating test set
  test = total_test[test_num]   # one PR is test in each examination
  # creating train set
  if test_num == 0:
    train = init_train
  else:
    train.append(total_test[test_num-1])
  
  # Do other calculations
  # extract 3 metrices
  FR = cal_expertise(train, test)
  print(FR)
  print("-------------------")
  DR = cal_collaboration(train, test)
  print(DR)
  # avail = cal_availability(train, test)
  # do genetic
  # ...



P is: 10653
M is: 82
Shape of FR matrix is: (10653, 82)
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]]
-------------------
N is: 10
M is: 82
Shape of DR matrix is: (10, 82)
[[  0   0   0   2   0   0   0   0   0   0 135   0   0   0   0   0   0   0
    0   0   0   0   0   0   1   0   0   5   0   0 386   0   0   0   0   0
    0   0   0   0   0   0  12   0   0   1   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   7   0   0   0   0   0   6
   11   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   7   0   0   0   0   4   0   3   0  12   1   0   0   0   0
  

In [114]:
train[0:5]

[{'changeId': 'I9e7b9a2491d6a3f01d71551e4cadcccf154d992d',
  'filePaths': ['tempest/tests/test_volumes_get.py'],
  'ownerId': '2238',
  'reviewersId': ['97', '7']},
 {'changeId': 'I10e7116570f922ec87e23b1f880cd4b1c08c3088',
  'filePaths': ['tempest/tests/identity/test_roles.py',
   'tempest/services/identity/json/admin_client.py',
   'tempest/tests/identity/base_admin_test.py'],
  'ownerId': '4120',
  'reviewersId': ['97', '7']},
 {'changeId': 'I1d0c395cf679e07e304dd878d97734307b685f4c',
  'filePaths': ['.gitignore'],
  'ownerId': '1849',
  'reviewersId': ['679', '1561']},
 {'changeId': 'Ia151f265bf62e6704de6cc2f2c01963be9e2dd69',
  'filePaths': ['tools/hacking.py'],
  'ownerId': '1849',
  'reviewersId': ['1561', '357']},
 {'changeId': 'Ie4cfec6f89d6b37554b5345cde92f982397915e2',
  'filePaths': ['tox.ini'],
  'ownerId': '2',
  'reviewersId': ['1561', '357']}]

In [115]:
test

{'changeId': 'I0064ddec13b090fe8a6b7c0dde2feda29d277828',
 'filePaths': ['manifests/site.pp'],
 'ownerId': '1',
 'reviewersId': ['2']}